spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dat_ve?useSLL=false&serverTimezone=UTC  # Database URL
    username: root  # Database username
    password: huythang02  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class name
  jpa:
    hibernate:
      ddl-auto: none  # Hibernate schema auto-update strategy
    show-sql: true  # Show SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect for MySQL 8
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 2592000 # in second
  refreshable-duration: 36000 # in seconds
api:
  prefix: api/v1
cloudinary:
  cloud-name: dsoz9gcfd
  api-key: 791357523784923
  api-secret: NgevDFEbDQCBM08mo5lsvW93l40