spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dat_ve?useSLL=false&serverTimezone=UTC
    username: root
    password: huythang02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

outbound:
  identity:
    client-id: "296253261995-l9h9uurvmsmb31l9lenrv3iau6p1c6lj.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000"

jwt:
  signerKey: "/4QGxOo+h7hFa4/maPoOzQqaSQs8FoRNm67ifE5FbYlDaiH+7mG3MflDHn1aWpeS"
  valid-duration: 6000000 #2592000 # in second
  refreshable-duration: 36000 # in seconds
api:
  prefix: api/v1
cloudinary:
  cloud-name: dsoz9gcfd
  api-key: 791357523784923
  api-secret: NgevDFEbDQCBM08mo5lsvW93l40

vnp:
  partnerCode: K126GZDF
  accessKey: ACCESS_KEY
  secretKey: AVUIGDB260WKO4IV9VJMDZGUDOZLHUQU
  endpoint: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html